@startuml
'https://plantuml.com/sequence-diagram

actor BOT
entity AddReviewsController
entity AddReviwsService
database DB #grey

BOT -> AddReviewsController : ADD AddReviews/{comment}
AddReviewsController -> AddReviwsService : ADD AddReviews/{comment}
AddReviwsService <-> DB
DB -> AddReviwsService : message "Комментарий добавлен"
AddReviwsService -> AddReviewsController : message "Комментарий добавлен"
AddReviewsController -> BOT : message "Комментарий добавлен"
@enduml